import {
  AfterViewChecked,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  OnInit,
  ViewChild,
  computed,
  effect,
  inject,
  signal
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import {
  ChatMode,
  ChatSession,
  VoyagerChatService
} from '../../core/services/voyager-chat.service';
import { AuthService } from '../../core/auth/auth.service';
import { ItineraryService } from '../../core/services/itinerary.service';
import { AlertService } from '../../core/services/alert.service';

declare global {
  interface Window {
    webkitSpeechRecognition?: any;
    SpeechRecognition?: any;
  }
}

type SessionGroup = {
  label: string;
  items: ChatSession[];
};

@Component({
  selector: 'app-voyager-ai',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './voyager-ai.component.html',
  styleUrls: ['./voyager-ai.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class VoyagerAiComponent implements OnInit, AfterViewChecked {
  protected readonly chatService = inject(VoyagerChatService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly authService = inject(AuthService);
  private readonly itineraryService = inject(ItineraryService);
  private readonly alertService = inject(AlertService);

  @ViewChild('scrollContainer') private scrollContainer?: ElementRef<HTMLDivElement>;

  readonly userName = signal('Viaggiatore');
  readonly userAvatar = signal<string | null>(null);
  readonly userInitial = signal('V');
  readonly searchTerm = signal('');
  readonly message = signal('');
  readonly pendingAttachmentName = signal<string | null>(null);
  readonly isGeneratingItinerary = signal(false);
  readonly isVoiceSupported = signal(false);
  readonly isListening = signal(false);
  readonly showMobileSidebar = signal(false);
  readonly isSwitchingSession = signal(false);
  readonly suppressSessionLoader = signal(false);
  readonly isPlannerLocked = computed(() => Boolean(
    this.chatService.activeSession()?.metadata?.plannerLocked ||
    this.chatService.activeSession()?.metadata?.generatedItineraryId
  ));

  readonly modalItineraryId = signal<number | null>(null);
  readonly modalItineraryPreview = signal<any | null>(null);
  readonly modalItineraryImages = signal<string[]>([]);

  readonly isSessionLoading = computed(() => {
    if (this.suppressSessionLoader()) return false;
    return (
      this.chatService.isLoadingSessions() ||
      this.chatService.isLoadingMessages() ||
      this.isSwitchingSession()
    );
  });

  readonly currentModeLabel = computed(() => (this.chatService.mode() === 'planner' ? 'Planner Mode' : 'Assistant Mode'));

  private speechRecognition: any = null;
  private lastPromptHandled: string | null = null;
  private lastAutoGeneratedSessionId: number | null = null;

  constructor() {
    // effect must run inside an injection context (constructor is valid)
    effect(() => {
      const ready = this.chatService.readyToGenerate();
      const msgs = this.chatService.messages().length;
      const active = this.chatService.activeSession();

      if (!active) return;
      if (!ready) return;
      if (msgs === 0) return;
      if (!active.metadata?.plannerState?.destination || !active.metadata?.plannerState?.locationId) return;
      if (this.lastAutoGeneratedSessionId === active.id) return;

      // mark and trigger generation/navigation once per session
      this.lastAutoGeneratedSessionId = active.id;
      void this.generateItinerary();
    });
  }

  formatMessageTime(value: string | Date | null | undefined): string {
    if (!value) {
      return '';
    }

    const parsedDate = value instanceof Date ? value : new Date(value);
    if (Number.isNaN(parsedDate.getTime())) {
      return '';
    }

    return parsedDate.toLocaleTimeString('it-IT', {
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  readonly plannerTemplates = [
    { label: 'Weekend Escape', text: 'Voglio organizzare un weekend escape di 3 giorni con ritmo rilassato e focus food.' },
    { label: 'Honeymoon', text: 'Sto pianificando un honeymoon dal taglio luxury con momenti romantici e cene speciali.' },
    { label: 'Foodie Trip', text: 'Vorrei un foodie trip con mercati locali, signature restaurants e quartieri autentici.' },
    { label: 'Road Adventure', text: 'Cerco un adventure road trip di 5 giorni con natura, tappe panoramiche e ritmo dinamico.' }
  ];

  readonly assistantTemplates = [
    { label: 'Best Restaurants', text: 'Quali sono i migliori quartieri food e ristoranti da non perdere?' },
    { label: 'Free Things', text: 'Cosa posso vedere gratis in città in 2 giorni?' },
    { label: 'Local Culture', text: 'Consigliami musei, mercati e luoghi culturali davvero memorabili.' },
    { label: 'Nightlife', text: 'Quali zone consigli per nightlife elegante e locali interessanti?' }
  ];

  readonly filteredSessions = computed(() => {
    const term = this.searchTerm().trim().toLowerCase();
    if (!term) return this.chatService.sessions();

    return this.chatService.sessions().filter((session) =>
      `${session.title || ''} ${session.metadata?.plannerState?.destination || ''}`.toLowerCase().includes(term)
    );
  });

  readonly pinnedSessions = computed(() =>
    this.filteredSessions().filter((session) => session.isPinned)
  );

  readonly recentSessionGroups = computed<SessionGroup[]>(() => {
    const unpinned = this.filteredSessions().filter((session) => !session.isPinned);
    const groups = new Map<string, ChatSession[]>();

    for (const session of unpinned) {
      const label = this.resolveSessionGroupLabel(session.lastMessageAt || session.createdAt);
      groups.set(label, [...(groups.get(label) || []), session]);
    }

    return Array.from(groups.entries()).map(([label, items]) => ({
      label,
      items: items.sort((left, right) => this.toTime(right) - this.toTime(left))
    }));
  });

  readonly quickPrompts = computed(() =>
    this.chatService.mode() === 'planner' ? this.plannerTemplates : this.assistantTemplates
  );

  readonly plannerHighlights = computed(() => {
    const state = this.chatService.plannerState();
    if (!state) return [];

    return [
      state.destination ? `Destinazione: ${state.destination}` : null,
      state.days ? `${state.days} giorni` : null,
      state.travelers ? `Viaggiatori: ${state.travelers}` : null,
      state.interests?.length ? `Interessi: ${state.interests.join(', ')}` : null,
      state.pace ? `Ritmo: ${state.pace}` : null,
      (state.style || state.hotelStyle) ? `Stile: ${state.style || state.hotelStyle}` : null
    ].filter((item): item is string => Boolean(item));
  });

  ngOnInit() {
    this.loadUserData();
    this.setupVoiceInput();

    const requestedSessionId = Number(this.route.snapshot.queryParams['sessionId']);
    const initialPrompt =
      typeof this.route.snapshot.queryParams['prompt'] === 'string'
        ? this.route.snapshot.queryParams['prompt'].trim()
        : '';
    const initialMode =
      this.route.snapshot.queryParams['mode'] === 'assistant' ? 'assistant' : 'planner';

    if (initialPrompt && this.lastPromptHandled !== initialPrompt) {
      this.lastPromptHandled = initialPrompt;
      this.suppressSessionLoader.set(true);
      void this.startNewChatWithPrompt(initialPrompt, initialMode);
    } else if (requestedSessionId) {
      this.chatService.loadSessions().subscribe({
        next: (sessions) => {
          const existing = sessions.find((session) => session.id === requestedSessionId);
          if (existing) {
            void this.selectSession(existing);
            return;
          }
          this.enterCleanLandingState();
        },
        error: (error) => this.handleChatAccessError(error)
      });
      return;
    } else {
      this.enterCleanLandingState();
    }

    this.chatService.loadSessions().subscribe({
      error: (error) => this.handleChatAccessError(error)
    });
  }

  ngAfterViewChecked() {
    this.scrollToBottom();
  }

  private loadUserData() {
    const data = this.authService.getUserData() as any;
    if (!data) return;

    this.userName.set(data.name || data.email || 'Viaggiatore');
    this.userAvatar.set(data.avatarUrl || null);
    this.userInitial.set((data.name || data.email || 'V').charAt(0).toUpperCase());
  }

  toggleSidebar() {
    this.chatService.isSidebarOpen.update((value) => !value);
  }

  toggleMobileSidebar() {
    this.showMobileSidebar.update((value) => !value);
  }

  goHome() {
    this.showMobileSidebar.set(false);
    this.router.navigate(['/home']);
  }

  openSettings() {
    this.showMobileSidebar.set(false);
    this.router.navigate(['/settings']);
  }

  openGeneratedItinerary() {
    const id = this.modalItineraryId();
    if (!id) return;
    void this.router.navigate(['/itineraries/builder'], { queryParams: { itineraryId: id } });
  }



  updateSessionTitle(event: Event) {
    const session = this.chatService.activeSession();
    if (!session) return;
    const input = event.target as HTMLInputElement;
    const newTitle = input.value.trim();
    if (newTitle && newTitle !== session.title) {
      this.chatService.updateSession(session.id, { title: newTitle }).subscribe(() => {
        // Optimistic update of the session title in the UI
        session.title = newTitle;
      });
    }
  }

  async createNewChat(mode: ChatMode = this.chatService.mode()) {
    const active = this.chatService.activeSession();
    const hasNoMessages = this.chatService.messages().length === 0;
    const hasDraftInput = !this.message().trim() && !this.pendingAttachmentName();

    if (active && hasNoMessages && hasDraftInput && active.mode === mode) {
      this.showMobileSidebar.set(false);
      this.router.navigate([], { queryParams: { sessionId: active.id }, queryParamsHandling: 'merge' });
      return;
    }

    this.isSwitchingSession.set(true);
    let session: ChatSession;
    try {
      session = await firstValueFrom(
        this.chatService.createSession({
          mode,
          title: mode === 'planner' ? 'Nuova sessione Planner' : 'Nuova sessione Assistant'
        })
      );
    } catch (error) {
      this.isSwitchingSession.set(false);
      this.handleChatAccessError(error);
      return;
    }

    this.chatService.setActiveSession(session);
    this.chatService.messages.set([]);
    this.isSwitchingSession.set(false);
    this.showMobileSidebar.set(false);
    this.router.navigate([], { queryParams: { sessionId: session.id }, queryParamsHandling: 'merge' });
  }

  startFreshPlanner() {
    this.enterCleanLandingState('planner');
  }

  startFreshAssistant() {
    this.enterCleanLandingState('assistant');
  }

  async selectSession(session: ChatSession) {
    this.isSwitchingSession.set(true);
    this.chatService.messages.set([]);
    this.chatService.setActiveSession(session);
    this.showMobileSidebar.set(false);
    try {
      await firstValueFrom(this.chatService.getSessionMessages(session.id));
      // If this session already has a generated itinerary, offer the user to open it
      const active = this.chatService.activeSession();
      const existing = active?.metadata?.generatedItinerary as any | undefined;
      const existingId = active?.metadata?.generatedItineraryId as number | undefined;
      if ((existing && existing.id) || existingId) {
        const id = existing?.id || existingId || null;
        this.modalItineraryId.set(id);
        if (id) {
          try {
            const it = await firstValueFrom(this.itineraryService.getItineraryById(id));
            this.modalItineraryPreview.set(it);
            // build images array (preview + items)
            const imgs: string[] = [];
            if (it?.imageUrl) imgs.push(it.imageUrl);
            if (Array.isArray(it?.items)) {
              for (const item of it.items) {
                const img = (item.activity && (item.activity as any).imageUrl) || (item.accommodation && (item.accommodation as any).imageUrl);
                if (img) imgs.push(img);
                if (imgs.length >= 4) break;
              }
            }
            this.modalItineraryImages.set(imgs.filter(Boolean).slice(0, 4));
          } catch (err) {
            this.modalItineraryPreview.set(null);
            this.modalItineraryImages.set([]);
          }
        }
      }
    } catch (error) {
      this.handleChatAccessError(error);
      return;
    } finally {
      this.isSwitchingSession.set(false);
    }
    this.router.navigate([], { queryParams: { sessionId: session.id }, queryParamsHandling: 'merge' });
  }

  togglePin(event: Event, session: ChatSession) {
    event.stopPropagation();
    this.chatService.updateSession(session.id, { isPinned: !session.isPinned }).subscribe();
  }

  deleteSession(event: Event, session: ChatSession) {
    event.stopPropagation();
    if (!confirm('Vuoi eliminare questa conversazione?')) return;

    this.chatService.deleteSession(session.id).subscribe(() => {
      if (this.chatService.activeSession()?.id === session.id) {
        this.chatService.clearActiveConversation(this.chatService.mode());
      }
    });
  }

  onSearch(term: string) {
    this.searchTerm.set(term);
  }

  async toggleMode(mode: ChatMode) {
    if (this.chatService.mode() === mode) return;

    const active = this.chatService.activeSession();
    if (!active) {
      this.enterCleanLandingState(mode);
      return;
    }

    if (this.chatService.messages().length === 0) {
      await this.createNewChat(mode);
      return;
    }

    this.enterCleanLandingState(mode);
  }

  async sendMessage() {
    if (!this.message().trim() || this.chatService.isStreaming() || this.isPlannerLocked()) return;

    const content = this.message().trim();
    this.message.set('');

    let active = this.chatService.activeSession();
    if (!active) {
      try {
        active = await firstValueFrom(
          this.chatService.createSession({
            mode: this.chatService.mode(),
            title: this.chatService.mode() === 'planner' ? 'Nuova sessione Planner' : 'Nuova sessione Assistant'
          })
        );
      } catch (error) {
        this.handleChatAccessError(error);
        return;
      }
    }

    await this.chatService.sendMessageStreaming(active.id, content, (data) => {
      if (data.metadata?.suggestedTitle) {
        this.router.navigate([], { queryParams: { sessionId: active!.id }, queryParamsHandling: 'merge' });
      }
    }).catch((error) => {
      this.handleChatAccessError(error);
    });
  }

  async usePrompt(prompt: string) {
    if (this.isPlannerLocked()) return;
    this.message.set(prompt);
    await this.sendMessage();
  }

  async startNewChatWithPrompt(prompt: string, mode: ChatMode = 'planner') {
    this.suppressSessionLoader.set(true);

    let session: ChatSession;
    try {
      session = await firstValueFrom(
        this.chatService.createSession({
          title: mode === 'assistant' ? 'Nuova sessione Assistant' : 'Voyager AI',
          mode
        })
      );
    } catch (error) {
      this.suppressSessionLoader.set(false);
      this.handleChatAccessError(error);
      return;
    }

    this.chatService.setActiveSession(session);
    void this.router.navigate([], {
      queryParams: { sessionId: session.id, prompt: null, mode: null },
      queryParamsHandling: 'merge',
      replaceUrl: true
    });

    await this.chatService.sendMessageStreaming(session.id, prompt, () => {}).catch((error) => {
      this.handleChatAccessError(error);
    }).finally(() => {
      this.suppressSessionLoader.set(false);
    });
  }

  async generateItinerary() {
    const session = this.chatService.activeSession();
    if (!session) return;

    if (this.isPlannerLocked()) {
      this.alertService.info('L’itinerario è già stato generato. Apri il builder per continuare le modifiche.');
      return;
    }

    // If the session already has a generated itinerary, reuse it instead of creating a new one
    const existing = session.metadata?.generatedItinerary as any | undefined;
    if (existing && existing.id) {
      this.itineraryService.setCurrentItinerary(existing, { autosave: false });
      this.chatService.setActiveSession({
        ...session,
        metadata: {
          ...(session.metadata || {}),
          plannerLocked: true,
          generatedItineraryId: existing.id,
          generatedItinerary: existing,
          readyToGenerate: true
        }
      });
      await this.router.navigate(['/itineraries/builder']);
      return;
    }

    this.isGeneratingItinerary.set(true);

    try {
      const response = await firstValueFrom(this.chatService.generateItinerary(session.id));
      this.itineraryService.setCurrentItinerary(response.itinerary, { autosave: false });

      // Update active session metadata so subsequent generate clicks reuse the same itinerary
      const updatedSession: any = {
        ...session,
        metadata: {
          ...(session.metadata || {}),
          generatedItinerary: response.itinerary,
          generatedItineraryId: response.itinerary.id,
          plannerLocked: true,
          readyToGenerate: true
        }
      };

      this.chatService.setActiveSession(updatedSession);
      this.chatService.sessions.update((sessions) => sessions.map((s) => (s.id === updatedSession.id ? updatedSession : s)));

      // Navigate to builder and include itinerary id in query for shareable URL
      await this.router.navigate(['/itineraries/builder'], { queryParams: { itineraryId: response.itinerary.id } });
    } catch (error: any) {
      this.handleChatAccessError(error);
      const message = error?.error?.message || 'In questo momento i servizi di Vojage ai sono in sovraccarico. Riprova tra un istante.';
      this.alertService.error(message);
    } finally {
      this.isGeneratingItinerary.set(false);
    }
  }

  exportConversation(format: 'md' | 'json') {
    const session = this.chatService.activeSession();
    if (!session) return;

    const payload =
      format === 'json'
        ? JSON.stringify(
          {
            session,
            messages: this.chatService.messages()
          },
          null,
          2
        )
        : this.chatService.messages()
          .map((message) => `## ${message.role === 'user' ? 'You' : 'Voyager AI'}\n\n${message.content}`)
          .join('\n\n');

    const blob = new Blob([payload], {
      type: format === 'json' ? 'application/json;charset=utf-8' : 'text/markdown;charset=utf-8'
    });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${(session.title || 'voyager-chat').replace(/\s+/g, '-').toLowerCase()}.${format}`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  async shareConversation() {
    const session = this.chatService.activeSession();
    if (!session) return;

    const shareUrl = `${window.location.origin}/voyager?sessionId=${session.id}`;

    if (navigator.share) {
      await navigator.share({
        title: session.title || 'Voyager AI',
        text: 'Ti condivido questa conversazione di viaggio SmartFare.',
        url: shareUrl
      });
      return;
    }

    await navigator.clipboard.writeText(shareUrl);
    this.alertService.success('Link conversazione copiato negli appunti.');
  }

  attachPlaceholder(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    this.pendingAttachmentName.set(file?.name || null);
  }

  clearAttachment() {
    this.pendingAttachmentName.set(null);
  }

  onEnter(event: Event) {
    const keyboardEvent = event as KeyboardEvent;
    if (keyboardEvent.shiftKey) return;
    event.preventDefault();
    this.sendMessage();
  }

  formatMessage(content: string): string {
    if (!content) return '';

    const escaped = this.escapeHtml(content);

    return escaped
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\n/g, '<br>');
  }

  private escapeHtml(value: string): string {
    return value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  private scrollToBottom() {
    if (!this.scrollContainer) return;
    this.scrollContainer.nativeElement.scrollTop = this.scrollContainer.nativeElement.scrollHeight;
  }

  private enterCleanLandingState(mode: ChatMode = this.chatService.mode()) {
    this.chatService.clearActiveConversation(mode);
    this.message.set('');
    this.pendingAttachmentName.set(null);
    this.isSwitchingSession.set(false);
    this.router.navigate([], {
      queryParams: {
        sessionId: null,
        prompt: null
      },
      queryParamsHandling: 'merge',
      replaceUrl: true
    });
  }

  private handleChatAccessError(error: unknown): boolean {
    if (!this.isAuthError(error)) {
      return false;
    }

    this.authService.Logout();
    this.chatService.clearActiveConversation(this.chatService.mode());
    this.isSwitchingSession.set(false);
    this.alertService.error('La sessione è scaduta. Accedi di nuovo per usare Voyager AI.');
    void this.router.navigate(['/login'], {
      queryParams: { returnUrl: '/voyager' }
    });
    return true;
  }

  private isAuthError(error: unknown): boolean {
    if (!(error instanceof HttpErrorResponse)) {
      return false;
    }

    return error.status === 401 || error.status === 403;
  }

  private resolveSessionGroupLabel(dateString: string): string {
    const date = new Date(dateString);
    const today = new Date();
    const yesterday = new Date();
    yesterday.setDate(today.getDate() - 1);

    if (this.isSameDay(date, today)) return 'Oggi';
    if (this.isSameDay(date, yesterday)) return 'Ieri';

    const diffInDays = Math.floor((today.getTime() - date.getTime()) / (1000 * 60 * 60 * 24));
    if (diffInDays <= 7) return 'Questa settimana';
    return 'Meno recenti';
  }

  private isSameDay(left: Date, right: Date): boolean {
    return (
      left.getFullYear() === right.getFullYear() &&
      left.getMonth() === right.getMonth() &&
      left.getDate() === right.getDate()
    );
  }

  private toTime(session: ChatSession): number {
    return new Date(session.lastMessageAt || session.createdAt).getTime();
  }

  private setupVoiceInput() {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    this.isVoiceSupported.set(Boolean(SpeechRecognition));

    if (!SpeechRecognition) return;

    this.speechRecognition = new SpeechRecognition();
    this.speechRecognition.lang = 'it-IT';
    this.speechRecognition.interimResults = true;
    this.speechRecognition.continuous = false;

    this.speechRecognition.onstart = () => this.isListening.set(true);
    this.speechRecognition.onend = () => this.isListening.set(false);
    this.speechRecognition.onresult = (event: any) => {
      const transcript = Array.from(event.results)
        .map((result: any) => result[0]?.transcript || '')
        .join(' ');

      this.message.set(transcript.trim());
    };
  }

  toggleVoiceInput() {
    if (!this.speechRecognition) return;

    if (this.isListening()) {
      this.speechRecognition.stop();
      return;
    }

    this.speechRecognition.start();
  }
}
