BEGIN;

CREATE TABLE IF NOT EXISTS "User" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "email" varchar(150) NOT NULL UNIQUE,
    "passwordHash" varchar(255),
    "authProvider" varchar(40) NOT NULL DEFAULT 'local',
    "sessionId" varchar(120),
    "resetPasswordToken" varchar(255),
    "resetPasswordExpires" timestamptz,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "UserProfile" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "userId" integer NOT NULL UNIQUE,
    "name" varchar(80),
    "surname" varchar(80),
    "city" varchar(80),
    "street" varchar(120),
    "avatarUrl" varchar(500),
    "birthDate" date,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "UserProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserPreference" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "userId" integer NOT NULL UNIQUE,
    "budgetLevelCode" varchar(20) NOT NULL DEFAULT 'MEDIUM',
    "travelStyle" varchar(40),
    "pace" varchar(40),
    "preferredTransport" varchar(40),
    "prefersNightlife" boolean,
    "familyFriendly" boolean,
    "maxDailyBudget" numeric(10, 2),
    "notes" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "UserPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserPreferenceInterest" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "preferenceId" integer NOT NULL,
    "activityCategoryId" integer NOT NULL,
    "weight" integer NOT NULL DEFAULT 1,
    CONSTRAINT "UserPreferenceInterest_preferenceId_fkey" FOREIGN KEY ("preferenceId") REFERENCES "UserPreference"("id") ON DELETE CASCADE,
    CONSTRAINT "UserPreferenceInterest_activityCategoryId_fkey" FOREIGN KEY ("activityCategoryId") REFERENCES "ActivityCategory"("id"),
    CONSTRAINT "UserPreferenceInterest_preferenceId_activityCategoryId_key" UNIQUE ("preferenceId", "activityCategoryId")
);

CREATE TABLE IF NOT EXISTS "GuestSession" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "sessionToken" varchar(120) NOT NULL UNIQUE,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "expiresAt" timestamptz NOT NULL,
    "ipAddress" varchar(64),
    "userAgent" varchar(255)
);

CREATE TABLE IF NOT EXISTS "ItineraryVisibility" (
    "code" varchar(20) PRIMARY KEY,
    "name" varchar(50) NOT NULL,
    "description" varchar(200)
);

CREATE TABLE IF NOT EXISTS "Itinerary" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(120) NOT NULL,
    "description" text,
    "isPublished" boolean NOT NULL DEFAULT false,
    "visibilityCode" varchar(20) NOT NULL DEFAULT 'PRIVATE',
    "publicSlug" varchar(180) UNIQUE,
    "startDate" date,
    "endDate" date,
    "aiPrompt" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "userId" integer,
    "guestSessionId" integer,
    CONSTRAINT "Itinerary_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE
    SET
        NULL,
        CONSTRAINT "Itinerary_guestSessionId_fkey" FOREIGN KEY ("guestSessionId") REFERENCES "GuestSession"("id") ON DELETE
    SET
        NULL,
        CONSTRAINT "Itinerary_visibilityCode_fkey" FOREIGN KEY ("visibilityCode") REFERENCES "ItineraryVisibility"("code")
);

CREATE TABLE IF NOT EXISTS "ItineraryFavorite" (
    "userId" integer NOT NULL,
    "itineraryId" integer NOT NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "ItineraryFavorite_pkey" PRIMARY KEY ("userId", "itineraryId"),
    CONSTRAINT "ItineraryFavorite_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE,
    CONSTRAINT "ItineraryFavorite_itineraryId_fkey" FOREIGN KEY ("itineraryId") REFERENCES "Itinerary"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ItineraryItemType" (
    "code" varchar(30) PRIMARY KEY,
    "label" varchar(50) NOT NULL,
    "description" varchar(200)
);

CREATE TABLE IF NOT EXISTS "Location" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(120) NOT NULL,
    "province" varchar(80),
    "cap" varchar(10),
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS "Accommodation" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(150) NOT NULL,
    "street" varchar(150),
    "stars" integer NOT NULL DEFAULT 0,
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL,
    "imageUrl" varchar(500),
    "locationId" integer NOT NULL,
    CONSTRAINT "Accommodation_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id")
);

CREATE TABLE IF NOT EXISTS "TransportType" (
    "code" varchar(30) PRIMARY KEY,
    "label" varchar(50) NOT NULL,
    "description" varchar(200)
);

CREATE TABLE IF NOT EXISTS "Transport" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "transportCode" varchar(30) NOT NULL UNIQUE,
    "transportType" varchar(30) NOT NULL,
    CONSTRAINT "Transport_transportType_fkey" FOREIGN KEY ("transportType") REFERENCES "TransportType"("code")
);

CREATE TABLE IF NOT EXISTS "Station" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(120) NOT NULL,
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL,
    "locationId" integer NOT NULL,
    CONSTRAINT "Station_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id")
);

CREATE TABLE IF NOT EXISTS "Airport" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(120) NOT NULL,
    "iataCode" varchar(10),
    "icaoCode" varchar(10),
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL,
    "locationId" integer NOT NULL,
    CONSTRAINT "Airport_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id")
);

CREATE TABLE IF NOT EXISTS "MetroStation" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(120) NOT NULL,
    "line" varchar(80),
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL,
    "locationId" integer NOT NULL,
    CONSTRAINT "MetroStation_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id")
);

CREATE TABLE IF NOT EXISTS "ActivityCategory" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(80) NOT NULL UNIQUE,
    "description" varchar(200),
    "iconUrl" varchar(500),
    "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Activity" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(150) NOT NULL,
    "description" text,
    "street" varchar(150),
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL,
    "imageUrl" varchar(500),
    "locationId" integer NOT NULL,
    "categoryId" integer NOT NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Activity_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id"),
    CONSTRAINT "Activity_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ActivityCategory"("id")
);

CREATE TABLE IF NOT EXISTS "RouteSegment" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "transportId" integer NOT NULL,
    "departureAt" timestamptz NOT NULL,
    "arrivalAt" timestamptz NOT NULL,
    "departureStationId" integer,
    "arrivalStationId" integer,
    "departureAirportId" integer,
    "arrivalAirportId" integer,
    "departureMetroStationId" integer,
    "arrivalMetroStationId" integer,
    CONSTRAINT "RouteSegment_transportId_fkey" FOREIGN KEY ("transportId") REFERENCES "Transport"("id"),
    CONSTRAINT "RouteSegment_departureStationId_fkey" FOREIGN KEY ("departureStationId") REFERENCES "Station"("id"),
    CONSTRAINT "RouteSegment_arrivalStationId_fkey" FOREIGN KEY ("arrivalStationId") REFERENCES "Station"("id"),
    CONSTRAINT "RouteSegment_departureAirportId_fkey" FOREIGN KEY ("departureAirportId") REFERENCES "Airport"("id"),
    CONSTRAINT "RouteSegment_arrivalAirportId_fkey" FOREIGN KEY ("arrivalAirportId") REFERENCES "Airport"("id"),
    CONSTRAINT "RouteSegment_departureMetroStationId_fkey" FOREIGN KEY ("departureMetroStationId") REFERENCES "MetroStation"("id"),
    CONSTRAINT "RouteSegment_arrivalMetroStationId_fkey" FOREIGN KEY ("arrivalMetroStationId") REFERENCES "MetroStation"("id")
);

CREATE TABLE IF NOT EXISTS "ItineraryItem" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "itineraryId" integer NOT NULL,
    "itemTypeCode" varchar(30) NOT NULL,
    "dayNumber" integer NOT NULL,
    "orderInt" integer NOT NULL,
    "note" varchar(400),
    "plannedStartAt" timestamptz,
    "plannedEndAt" timestamptz,
    "activityId" integer,
    "accommodationId" integer,
    "routeSegmentId" integer,
    CONSTRAINT "ItineraryItem_itineraryId_fkey" FOREIGN KEY ("itineraryId") REFERENCES "Itinerary"("id") ON DELETE CASCADE,
    CONSTRAINT "ItineraryItem_itemTypeCode_fkey" FOREIGN KEY ("itemTypeCode") REFERENCES "ItineraryItemType"("code"),
    CONSTRAINT "ItineraryItem_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE
    SET
        NULL,
        CONSTRAINT "ItineraryItem_accommodationId_fkey" FOREIGN KEY ("accommodationId") REFERENCES "Accommodation"("id") ON DELETE
    SET
        NULL,
        CONSTRAINT "ItineraryItem_routeSegmentId_fkey" FOREIGN KEY ("routeSegmentId") REFERENCES "RouteSegment"("id") ON DELETE
    SET
        NULL,
        CONSTRAINT "ItineraryItem_itineraryId_dayNumber_orderInt_key" UNIQUE ("itineraryId", "dayNumber", "orderInt")
);

CREATE INDEX IF NOT EXISTS "User_email_idx" ON "User" ("email");

CREATE INDEX IF NOT EXISTS "UserPreference_budgetLevelCode_idx" ON "UserPreference" ("budgetLevelCode");

CREATE INDEX IF NOT EXISTS "UserPreferenceInterest_activityCategoryId_idx" ON "UserPreferenceInterest" ("activityCategoryId");

CREATE INDEX IF NOT EXISTS "GuestSession_expiresAt_idx" ON "GuestSession" ("expiresAt");

CREATE INDEX IF NOT EXISTS "Itinerary_userId_idx" ON "Itinerary" ("userId");

CREATE INDEX IF NOT EXISTS "Itinerary_guestSessionId_idx" ON "Itinerary" ("guestSessionId");

CREATE INDEX IF NOT EXISTS "Itinerary_isPublished_idx" ON "Itinerary" ("isPublished");

CREATE INDEX IF NOT EXISTS "Itinerary_visibilityCode_idx" ON "Itinerary" ("visibilityCode");

CREATE INDEX IF NOT EXISTS "Itinerary_createdAt_idx" ON "Itinerary" ("createdAt");

CREATE INDEX IF NOT EXISTS "ItineraryFavorite_itineraryId_idx" ON "ItineraryFavorite" ("itineraryId");

CREATE INDEX IF NOT EXISTS "ItineraryItem_itineraryId_idx" ON "ItineraryItem" ("itineraryId");

CREATE INDEX IF NOT EXISTS "ItineraryItem_itemTypeCode_idx" ON "ItineraryItem" ("itemTypeCode");

CREATE INDEX IF NOT EXISTS "ItineraryItem_dayNumber_idx" ON "ItineraryItem" ("dayNumber");

CREATE INDEX IF NOT EXISTS "Location_name_idx" ON "Location" ("name");

CREATE INDEX IF NOT EXISTS "Accommodation_locationId_idx" ON "Accommodation" ("locationId");

CREATE INDEX IF NOT EXISTS "Accommodation_name_idx" ON "Accommodation" ("name");

CREATE INDEX IF NOT EXISTS "Transport_transportType_idx" ON "Transport" ("transportType");

CREATE INDEX IF NOT EXISTS "RouteSegment_transportId_idx" ON "RouteSegment" ("transportId");

CREATE INDEX IF NOT EXISTS "RouteSegment_departureStationId_idx" ON "RouteSegment" ("departureStationId");

CREATE INDEX IF NOT EXISTS "RouteSegment_arrivalStationId_idx" ON "RouteSegment" ("arrivalStationId");

CREATE INDEX IF NOT EXISTS "RouteSegment_departureAirportId_idx" ON "RouteSegment" ("departureAirportId");

CREATE INDEX IF NOT EXISTS "RouteSegment_arrivalAirportId_idx" ON "RouteSegment" ("arrivalAirportId");

CREATE INDEX IF NOT EXISTS "RouteSegment_departureMetroStationId_idx" ON "RouteSegment" ("departureMetroStationId");

CREATE INDEX IF NOT EXISTS "RouteSegment_arrivalMetroStationId_idx" ON "RouteSegment" ("arrivalMetroStationId");

CREATE INDEX IF NOT EXISTS "RouteSegment_departureAt_idx" ON "RouteSegment" ("departureAt");

CREATE INDEX IF NOT EXISTS "Station_locationId_idx" ON "Station" ("locationId");

CREATE INDEX IF NOT EXISTS "Station_name_idx" ON "Station" ("name");

CREATE INDEX IF NOT EXISTS "Airport_locationId_idx" ON "Airport" ("locationId");

CREATE INDEX IF NOT EXISTS "Airport_name_idx" ON "Airport" ("name");

CREATE INDEX IF NOT EXISTS "MetroStation_locationId_idx" ON "MetroStation" ("locationId");

CREATE INDEX IF NOT EXISTS "MetroStation_name_idx" ON "MetroStation" ("name");

CREATE INDEX IF NOT EXISTS "Activity_locationId_idx" ON "Activity" ("locationId");

CREATE INDEX IF NOT EXISTS "Activity_categoryId_idx" ON "Activity" ("categoryId");

CREATE INDEX IF NOT EXISTS "Activity_name_idx" ON "Activity" ("name");

COMMIT;